// Adjust this import to wherever your Supabase client is instantiated
// (same client used by eventService, e.g. src/lib/supabase.ts)
import { supabase } from "@/lib/supabase/clientSupabase";
import type { BookingData, Order, IssuedTicket } from "@/types/orderTypes";

interface CreateOrderPayload {
  booking: BookingData;
  clientName: string;
  clientEmail: string;
  clientPhone: string;
}

export const orderService = {
  /**
   * Creates one order row + one ticket row per unit purchased.
   * Throws with a user-friendly message on failure.
   */
  async createOrderWithTickets(
    payload: CreateOrderPayload,
  ): Promise<{ order: Order; tickets: IssuedTicket[] }> {
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      throw new Error("Vous devez être connecté pour réserver des billets.");
    }

    const { booking, clientName, clientEmail, clientPhone } = payload;

    // 1. Create the order
    const { data: orderRow, error: orderError } = await supabase
      .from("orders")
      .insert({
        user_id: user.id,
        event_id: booking.event.id,
        total_price: booking.totalPrice,
        currency: booking.event.currency || "EUR",
        // NOTE: no payment provider is wired up yet, so we mark the order
        // 'paid' directly for this demo flow. Once you plug in a real
        // payment gateway, create the order as 'pending' here and flip it
        // to 'paid' from a server-side webhook after payment confirmation.
        status: "paid",
        client_name: clientName,
        client_email: clientEmail,
        client_phone: clientPhone,
      })
      .select()
      .single();

    if (orderError || !orderRow) {
      throw new Error(
        orderError?.message || "Impossible de créer la réservation.",
      );
    }

    // 2. Expand each ticket type into individual ticket rows
    const ticketsToInsert = booking.items.flatMap((item) =>
      Array.from({ length: item.quantity }).map(() => ({
        order_id: orderRow.id,
        event_id: booking.event.id,
        user_id: user.id,
        ticket_type_id: item.ticketTypeId,
        client_name: clientName,
        client_email: clientEmail,
        client_phone: clientPhone,
        price: item.price,
        // unique_code / qr_code are auto-generated by the DB trigger
      })),
    );

    const { data: ticketRows, error: ticketError } = await supabase
      .from("tickets")
      .insert(ticketsToInsert)
      .select();

    if (ticketError || !ticketRows) {
      // Roll back: cancel the order if ticket creation failed
      await supabase
        .from("orders")
        .update({ status: "cancelled" })
        .eq("id", orderRow.id);
      throw new Error(
        ticketError?.message || "Impossible de générer les billets.",
      );
    }

    return {
      order: mapOrder(orderRow),
      tickets: ticketRows.map(mapTicket),
    };
  },

  /** Fetch an order and its tickets, e.g. to reload a confirmation page */
  async getOrderWithTickets(
    orderId: string,
  ): Promise<{ order: Order; tickets: IssuedTicket[] }> {
    const { data: orderRow, error: orderError } = await supabase
      .from("orders")
      .select()
      .eq("id", orderId)
      .single();

    if (orderError || !orderRow) throw new Error("Réservation introuvable.");

    const { data: ticketRows, error: ticketError } = await supabase
      .from("tickets")
      .select()
      .eq("order_id", orderId);

    if (ticketError) throw new Error(ticketError.message);

    return {
      order: mapOrder(orderRow),
      tickets: (ticketRows || []).map(mapTicket),
    };
  },
};

function mapOrder(row: any): Order {
  return {
    id: row.id,
    userId: row.user_id,
    eventId: row.event_id,
    totalPrice: row.total_price,
    currency: row.currency,
    status: row.status,
    clientName: row.client_name,
    clientEmail: row.client_email,
    clientPhone: row.client_phone,
    paymentMethod: row.payment_method,
    paymentReference: row.payment_reference,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function mapTicket(row: any): IssuedTicket {
  return {
    id: row.id,
    orderId: row.order_id,
    eventId: row.event_id,
    userId: row.user_id,
    ticketTypeId: row.ticket_type_id,
    clientName: row.client_name,
    clientEmail: row.client_email,
    clientPhone: row.client_phone,
    price: row.price,
    uniqueCode: row.unique_code,
    qrCode: row.qr_code,
    isUsed: row.is_used,
    usedAt: row.used_at,
    createdAt: row.created_at,
  };
}
